### ISSUE TITLE
Yianni#1 - Function to create a File-Pagarism-Analysis Dictionary

### ISSUE THREAD

**Issue by ShlomoStept** [Darmis-Org-temp/zenhub-home#18]
Also -- Seperate out (each of the 3 parts) of the function, into their own function

**Comment by Yaythegreatgit** [comment]
Moss produces dictionaries of the form:
{
"filename" : "File.txt",
"score" : 1.0 ,
"plagerized_files": {
"file_1" : {
1:[ # first occurance of a plagerism
( File.txt_start_location, File.txt_end_location ), ( file_1__start_location , file_1__end_location )
]
2:[ # second occurance of a plagerism
( File.tx_start_location, File.tx_end_location ), ( file_1__start_location , file_1__end_location )
]
}
"file_2" : {
1:[ # first occurance of a plagerism
( File.txt_start_location, File.txt_end_location ), ( file_2__start_location , file_2__end_location )
]
2:[ # second occurance of a plagerism
( File.tx_start_location, File.tx_end_location ), ( file_2__start_location , file_2__end_location )]
]
}
}
}
